### ISSUE TITLE
HEAD detached at v7.4.1, Could not resolve com.github.fiskurgit:ChipCloud:3.0.3

### ISSUE THREAD

**Issue by gspeiliu** [klinker-apps/talon-for-twitter-android#131]
Hi,

I tried to build it on my own by using the command "./gradlew build" on tag v7.4.1, however, the error message about ChipCloud is still showing. Cloud you please take a look at it and give me some guidance. Thanks.

BTW, the website jitpack.io needs a user name and password.

Thanks for your help.

**Comment by klinker24** [comment]
jitpack does not need a user name and password and we are using a local version of chipcloud. Sorry, but I do not know what you mean. 

If you are getting a message telling you are you on a detached head, then you aren't building off the master branch. If you are on the tag for v7.4.1, then you are attempting to build a version of the app that is a year and a half old. This is not something I will be supporting.

```
git pull
git checkout master
./gradlew build
```
