### ISSUE TITLE
Twitter Threads are not always shown as threads

### ISSUE THREAD

**Issue by novoid** [klinker-apps/talon-for-twitter-android#133]
Hi,

With my Talon 7.7.7.2192 (and previous versions), I don't (always) see a twitter thread when I click on it in case it is a mentioned Tweet.

Example: Person X is tweeting:

- [...]
- X40
- X41
- X42 (thread)
  - X43
  - X44
  - X45
- X46 (non-thread)

Now, Person Y is mentioning X42 in her Tweet:
- Y23: "This is an amazing thread" (Talon displays a Tweet preview of X42)

Now, clicking on this preview of X42 shows me only X42 with its direct "reactions" from other users like "Z853: What a great thread!". What I don't see is "X42, X43, X44, X45".

Somehow, this issues is not present in 100% of the cases. I, unfortunately, can not tell you when this happens and when not.

Maybe the difference is when there are reactions to X42 or not. Maybe it's when Y is not mentioning X42 but X43? I don't have a second Twitter account to test this properly.

**Comment by klinker24** [comment]
I highly doubt that Twitter threads will ever improve within the app. Twitter has no official API or services for them. All that talon can do is perform a generic search against tweets and the user profiles. 

If Twitter were to provide an API for threads, I could fix these issues. As it is though, I do not see any improvements coming, unfortunately.
