### ISSUE TITLE
Add "Top Tweets First" order option

### ISSUE THREAD

**Issue by serovar** [klinker-apps/talon-for-twitter-android#145]
The one feature that every third-party client that I know of lacks is the possibility to use the "Top Tweets First" order for the feed. Since no one implemented it I suppose that it is not possible using the Twitter API v1, but maybe it could be possible using API v2?

**Comment by klinker24** [comment]
Sorry, no. Twitter provides the tweets in chronological order to third party apps. This isn't going to be possible

**Comment by serovar** [comment]
Just to know it (since no one seems to be able to answer this specific question), do you know for a fact that API v2 does not allow the use of this feature and that it gives the chronological order just like API v1?

**Comment by klinker24** [comment]
The v2 apis do not currently provide a user's "home" timeline. There is no reason to believe that twitter would provide anything but chronological. Creating a third party app is not the use-case that Twitter appears to be focusing on for their v2 apis.

https://developer.twitter.com/en/docs/twitter-api/tweets/search/introduction

**Comment by serovar** [comment]
Thanks!
