### ISSUE TITLE
Image compression when saving images

### ISSUE THREAD

**Issue by beriah** [klinker-apps/talon-for-twitter-android#147]
Sorry to reference https://github.com/klinker-apps/talon-for-twitter-android/issues/105 again when it's been closed for years but this is still an issue that persists.

![EqwAluBW8AIqVpT](https://user-images.githubusercontent.com/1399263/111149991-d677f200-858d-11eb-8699-f68ebee67cce.jpg)
![Image-644091](https://user-images.githubusercontent.com/1399263/111149802-a0d30900-858d-11eb-999c-92dbe98cc5f8.jpg)
First image is straight from Twitter (link: https://pbs.twimg.com/media/EqwAluBW8AIqVpT?format=jpg&name=orig), the other one is saved via Talon. You can clearly see the second one is compressed and has washed out colors.
Tweet in question for reference: https://twitter.com/NaturelsWeird/status/1366112183151648769

Any chance you could look into this?

**Comment by klinker24** [comment]
That old issue is still open, so it is something I can explore in the future. No need to duplicate it here
