### ISSUE TITLE
Shortlist of share options

### ISSUE THREAD

**Issue by noamross** [klinker-apps/talon-for-twitter-android#149]
Typically when I share a link or link to a tweet, it's to one of a small number (~3) apps, but in the only option is to designate an "always share" app, or choose from a list of all possible apps, in an indeterminate order.  Would it be possible to, say, show the top-used options at the top of the list?  Thank you.

**Comment by klinker24** [comment]
Unfortunately developers cannot control the order that those apps appear. That is a system level dialog, not a Talon dialog
