### ISSUE TITLE
talon-for-twitter-android/app/keystore' specified for property 'signingConfig.signingConfigData.storeFile' does not exist.

### ISSUE THREAD

**Issue by VincentJoshuaET** [klinker-apps/talon-for-twitter-android#151]
```
A problem was found with the configuration of task ':app:packageRelease' (type 'PackageApplication').
> File '/Users/vincentjoshuaet/GitHub/talon-for-twitter-android/app/keystore' specified for property 'signingConfig.signingConfigData.storeFile' does not exist.
```

It seems that we have to put the keystore file in every module folder.

**Comment by klinker24** [comment]
I store the keystore on my CI and use an absolute path to it. This is only required for release versions of the app. If you are making a release version, then I would think you changed the app enough to have your own fork. Feel free to change how the signing and release process works in your fork, or just use a debug build. I don't think I will be changing the signing setup in the main app
